language: node_js
node_js: node
sudo: false

notifications:
  email: false

before_script:
  - npm prune

script:
  - npm run build
  - npm run cover
  - npm run lint
  - npm run duplication -- --limit 1

after_success:
  - npm run semantic-release
